# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
os:
  - linux
cache:
  packages: true
r:
  - bioc-devel
before_install:
  - tlmgr install index